# Generated by Django 5.0.3 on 2024-06-03 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('points', models.IntegerField()),
                ('gem', models.CharField(choices=[('diamond', 'Diamond'), ('sapphire', 'Sapphire'), ('emerald', 'Emerald'), ('ruby', 'Ruby'), ('onyx', 'Onyx')], max_length=20)),
                ('cost', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nobel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('cost', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('gems', models.CharField(max_length=100)),
                ('purchased_cards', models.CharField(max_length=1000)),
                ('reserved_cards', models.CharField(max_length=1000)),
                ('nobles', models.CharField(max_length=200)),
                ('is_turn', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(max_length=1000)),
                ('gems_available', models.CharField(max_length=500)),
                ('nobles', models.CharField(max_length=200)),
                ('players', models.CharField(max_length=150)),
                ('current_turn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_turn', to='Game.player')),
            ],
        ),
    ]
