# Generated by Django 5.0.3 on 2024-06-03 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nobel',
            new_name='Noble',
        ),
    ]
