# Generated by Django 5.0.3 on 2024-06-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_rename_nobel_noble'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=20)),
                ('game_master_id', models.IntegerField()),
                ('num_players', models.IntegerField()),
                ('players', models.CharField(max_length=1000)),
            ],
        ),
    ]
